[versions]
org-jetbrains-kotlin = "1.7.10"
org-springframework = { prefer = "5.3.23" }
org-springframework-boot = { prefer = "2.7.5" }
com-vanniktech-gradle-maven-publish = "0.22.0"
org-slf4j = { prefer = "1.7.36" }
kotlin-logging-jvm = "2.1.23"
ch-qos-logback = { prefer = "1.4.4" }

[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "org-slf4j" }
javax-jaxb = { module = "javax.xml.bind:jaxb-api", version = "2.3.1" }
bom-springboot = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "org-springframework-boot" }
spring-context = { module = "org.springframework:spring-context", version.ref = "org-springframework" }
springboot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure", version.ref = "org-springframework-boot" }
springboot-test = { module = "org.springframework.boot:spring-boot-test", version.ref = "org-springframework-boot" }
springboot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "org-springframework-boot" }
springboot-starter-logging = { module = "org.springframework.boot:spring-boot-starter-logging", version.ref = "org-springframework-boot" }
springboot-starter-aop = { module = "org.springframework.boot:spring-boot-starter-aop", version.ref = "org-springframework-boot" }
kotlin-logging-jvm = { module = "io.github.microutils:kotlin-logging-jvm", version.ref = "kotlin-logging-jvm" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "ch-qos-logback" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin" }
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "org-jetbrains-kotlin" }
kotlin-noarg = { id = "org.jetbrains.kotlin.plugin.noarg", version.ref = "org-jetbrains-kotlin" }
springboot = { id = "org.springframework.boot", version.ref = "org-springframework-boot" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "com-vanniktech-gradle-maven-publish" }
